project:
  type: book
  output-dir: docs

book:
  title: "kenai_salmon_data"
  author: "Benjamin Meyer"
  page-navigation: true
  date: "3/9/2024"
  chapters:
    - index.qmd
    - data_sources.qmd
    - summary.qmd
    - references.qmd
    
  #repo-url: https://github.com/Kenai-Watershed-Forum/kenai-river-wqx-qaqc
  search:
    location: sidebar
    type: textbox
  downloads: [docx]

bibliography: references.bib

format:
  html:
    theme: cosmo
  docx:
    toc: true
    toc-depth: 2
    toc-title: Table of contents
    number-sections: true
    highlight-style: github
 # pdf:
 #    documentclass: scrreprt

editor: visual

