project:
  type: book
  output-dir: docs

book:
  title: "Tangled Nets: The Changing Faces of Northern Kenai Peninsula Salmon Fisheries [DRAFT IN PROGRESS]"
  author: "Benjamin Meyer, Rivulet Research"
  date: "`r Sys.Date()`"
  page-navigation: true
  url: "https://www.benjamin-meyer.net"
  chapters:
    - index.qmd
    - data_sources.qmd
    - summary.qmd
    - references.qmd
    
  repo-url: https://github.com/benjamin-meyer-ak/kenai_salmon
  repo-actions: [edit]
  search:
    location: sidebar
    type: textbox
  downloads: [docx]

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-summary: "Show the code"
    prefer-html: true
  docx:
    toc: true
    toc-depth: 2
    toc-title: Table of contents
    number-sections: true
    highlight-style: github
 # pdf:
 #    documentclass: scrreprt

editor: visual



